import { JapaneseLetter } from "../../core/models/japanese-letter";

export const japaneseLetterList: JapaneseLetter[] = [
   { romaji: "a", hiragana: "あ", katakana: "ア", weight: 1.6 },
   { romaji: "i", hiragana: "い", katakana: "イ", weight: 6.4 },
   { romaji: "u", hiragana: "う", katakana: "ウ", weight: 2.6 },
   { romaji: "e", hiragana: "え", katakana: "エ" },
   { romaji: "o", hiragana: "お", katakana: "オ" },
   { romaji: "ka", hiragana: "か", katakana: "カ", weight: 3.6 },
   { romaji: "ki", hiragana: "き", katakana: "キ" },
   { romaji: "ku", hiragana: "く", katakana: "ク", weight: 1.8 },
   { romaji: "ke", hiragana: "け", katakana: "ケ" },
   { romaji: "ko", hiragana: "こ", katakana: "コ", weight: 1.9 },
   { romaji: "sa", hiragana: "さ", katakana: "サ" },
   { romaji: "shi", hiragana: "し", katakana: "シ", weight: 4.3 },
   { romaji: "su", hiragana: "す", katakana: "ス", weight: 1.4 },
   { romaji: "se", hiragana: "せ", katakana: "セ" },
   { romaji: "so", hiragana: "そ", katakana: "ソ", weight: 2.1 },
   { romaji: "ta", hiragana: "た", katakana: "タ", weight: 5.8 },
   { romaji: "chi", hiragana: "ち", katakana: "チ" },
   { romaji: "tsu", hiragana: "つ", katakana: "ツ" },
   { romaji: "te", hiragana: "て", katakana: "テ", weight: 5.2 },
   { romaji: "to", hiragana: "と", katakana: "ト", weight: 4.4 },
   { romaji: "na", hiragana: "な", katakana: "ナ", weight: 4.2 },
   { romaji: "ni", hiragana: "に", katakana: "ニ", weight: 5.4 },
   { romaji: "nu", hiragana: "ぬ", katakana: "ヌ" },
   { romaji: "ne", hiragana: "ね", katakana: "ネ" },
   { romaji: "no", hiragana: "の", katakana: "ノ", weight: 8.4 },
   { romaji: "ha", hiragana: "は", katakana: "ハ", weight: 4.3 },
   { romaji: "hi", hiragana: "ひ", katakana: "ヒ" },
   { romaji: "fu", hiragana: "ふ", katakana: "フ" },
   { romaji: "he", hiragana: "へ", katakana: "ヘ" },
   { romaji: "ho", hiragana: "ほ", katakana: "ホ" },
   { romaji: "ma", hiragana: "ま", katakana: "マ", weight: 2.2 },
   { romaji: "mi", hiragana: "み", katakana: "ミ" },
   { romaji: "mu", hiragana: "む", katakana: "ム" },
   { romaji: "me", hiragana: "め", katakana: "メ" },
   { romaji: "mo", hiragana: "も", katakana: "モ", weight: 2.9 },
   { romaji: "ya", hiragana: "や", katakana: "ヤ" },
   { romaji: "yu", hiragana: "ゆ", katakana: "ユ" },
   { romaji: "yo", hiragana: "よ", katakana: "ヨ" },
   { romaji: "ra", hiragana: "ら", katakana: "ラ", weight: 2.5 },
   { romaji: "ri", hiragana: "り", katakana: "リ", weight: 2.0 },
   { romaji: "ru", hiragana: "る", katakana: "ル", weight: 3.9 },
   { romaji: "re", hiragana: "れ", katakana: "レ", weight: 2.4 },
   { romaji: "ro", hiragana: "ろ", katakana: "ロ" },
   { romaji: "wa", hiragana: "わ", katakana: "ワ" },
   { romaji: "wo", hiragana: "を", katakana: "ヲ", weight: 3.7 },
   { romaji: "n", hiragana: "ん", katakana: "ン", weight: 1.7 },
   { romaji: "ga", hiragana: "が", katakana: "ガ", weight: 2.8 },
   { romaji: "gi", hiragana: "ぎ", katakana: "ギ" },
   { romaji: "gu", hiragana: "ぐ", katakana: "グ" },
   { romaji: "ge", hiragana: "げ", katakana: "ゲ" },
   { romaji: "go", hiragana: "ご", katakana: "ゴ" },
   { romaji: "za", hiragana: "ざ", katakana: "ザ" },
   { romaji: "ji", hiragana: "じ", katakana: "ジ" },
   { romaji: "zu", hiragana: "ず", katakana: "ズ" },
   { romaji: "ze", hiragana: "ぜ", katakana: "ゼ" },
   { romaji: "zo", hiragana: "ぞ", katakana: "ゾ" },
   { romaji: "da", hiragana: "だ", katakana: "ダ" },
   { romaji: "ji", hiragana: "ぢ", katakana: "ヂ" },
   { romaji: "zu", hiragana: "づ", katakana: "ヅ" },
   { romaji: "de", hiragana: "で", katakana: "デ", weight: 3.5 },
   { romaji: "do", hiragana: "ど", katakana: "ド", weight: 1.3 },
   { romaji: "ba", hiragana: "ば", katakana: "バ" },
   { romaji: "bi", hiragana: "び", katakana: "ビ" },
   { romaji: "bu", hiragana: "ぶ", katakana: "ブ" },
   { romaji: "be", hiragana: "べ", katakana: "ベ" },
   { romaji: "bo", hiragana: "ぼ", katakana: "ボ" },
   { romaji: "pa", hiragana: "ぱ", katakana: "パ" },
   { romaji: "pi", hiragana: "ぴ", katakana: "ピ" },
   { romaji: "pu", hiragana: "ぷ", katakana: "プ" },
   { romaji: "pe", hiragana: "ぺ", katakana: "ペ" },
   { romaji: "po", hiragana: "ぽ", katakana: "ポ" },
   { romaji: "kya", hiragana: "きゃ", katakana: "キャ" },
   { romaji: "kyu", hiragana: "きゅ", katakana: "キュ" },
   { romaji: "kyo", hiragana: "きょ", katakana: "キョ" },
   { romaji: "sha", hiragana: "しゃ", katakana: "シャ" },
   { romaji: "shu", hiragana: "しゅ", katakana: "シュ" },
   { romaji: "sho", hiragana: "しょ", katakana: "ショ" },
   { romaji: "cha", hiragana: "ちゃ", katakana: "チャ" },
   { romaji: "chu", hiragana: "ちゅ", katakana: "チュ" },
   { romaji: "cho", hiragana: "ちょ", katakana: "チョ" },
   { romaji: "nya", hiragana: "にゃ", katakana: "ニャ" },
   { romaji: "nyu", hiragana: "にゅ", katakana: "ニュ" },
   { romaji: "nyo", hiragana: "にょ", katakana: "ニョ" },
   { romaji: "hya", hiragana: "ひゃ", katakana: "ヒャ" },
   { romaji: "hyu", hiragana: "ひゅ", katakana: "ヒュ" },
   { romaji: "hyo", hiragana: "ひょ", katakana: "ヒョ" },
   { romaji: "mya", hiragana: "みゃ", katakana: "ミャ" },
   { romaji: "myu", hiragana: "みゅ", katakana: "ミュ" },
   { romaji: "myo", hiragana: "みょ", katakana: "ミョ" },
   { romaji: "rya", hiragana: "りゃ", katakana: "リャ" },
   { romaji: "ryu", hiragana: "りゅ", katakana: "リュ" },
   { romaji: "ryo", hiragana: "りょ", katakana: "リョ" },
   { romaji: "gya", hiragana: "ぎゃ", katakana: "ギャ" },
   { romaji: "gyu", hiragana: "ぎゅ", katakana: "ギュ" },
   { romaji: "gyo", hiragana: "ぎょ", katakana: "ギョ" },
   { romaji: "ja", hiragana: "じゃ", katakana: "ジャ" },
   { romaji: "ju", hiragana: "じゅ", katakana: "ジュ" },
   { romaji: "jo", hiragana: "じょ", katakana: "ジョ" },
   { romaji: "bya", hiragana: "びゃ", katakana: "ビャ" },
   { romaji: "byu", hiragana: "びゅ", katakana: "ビュ" },
   { romaji: "byo", hiragana: "びょ", katakana: "ビョ" },
   { romaji: "pya", hiragana: "ぴゃ", katakana: "ピャ" },
   { romaji: "pyu", hiragana: "ぴゅ", katakana: "ピュ" },
   { romaji: "pyo", hiragana: "ぴょ", katakana: "ピョ" }
];
